version: "3.9"

services:
  cuda16:
    env_file: .env
    environment:
      - USER_NAME
      - USER_UID
      - USER_GID
      - CONTAINER_NAME
      - IMAGE_NAME
      - DEFAULT_TERM
      - DEFAULT_SHELL
      - DISPLAY
      - QT_X11_NO_MITSHM
      - NVIDIA_DRIVER_CAPABILITIES
    image: ${IMAGE_NAME}
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    network_mode: host
    container_name: ${CONTAINER_NAME}
    user: ${USER_NAME}
    volumes:
      - ~/.ssh:/home/${USER_NAME}/.ssh
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ~/.gitconfig:/home/${USER_NAME}/.gitconfig
      - ../:/home/${USER_NAME}/workspace/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /home/${USER_NAME}/workspace
    init: true
    stdin_open: false
    tty: true
    command: ["/bin/bash", "-c", "trap 'exit 0' TERM; sleep infinity & wait"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
